version: '2'

services:
  hapi:
    image: shawnmaten/hapi
    links:
      - db:db
    ports:
      - 80:80
    volumes:
      - ./:/usr/src/app
    env_file: .env

  db:
    image: tutum/mongodb
    environment:
      - AUTH=no

  dbtest:
    image: tutum/mongodb
    links:
      - db:db
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: /bin/bash

  vim:
    build:
      context: ./
      dockerfile: ./dockerfiles/vim
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
