version: '2'

services:
  hapi:
    extends:
      file: common.yml
      service: hapi
    links:
      - db:db
    volumes:
      - ./:/usr/src/app
    environment:
      - ENV=dev
      - BASE_URL=http://192.168.99.100

  db:
    extends:
      file: common.yml
      service: db

  dbtest:
    image: tutum/mongodb
    links:
      - db:db
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: /bin/bash

  vim:
    build:
      context: ./
      dockerfile: ./dockerfiles/vim
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
